# Generated by Django 5.0.1 on 2025-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_booking_seat_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatbooking',
            name='booking',
        ),
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='flight',
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='SeatBooking',
        ),
    ]
