# Generated by Django 5.0.1 on 2025-04-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_remove_seatbooking_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number',
        ),
    ]
