# Generated by Django 5.0.1 on 2025-04-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_rename_seat_number_passenger_seat_number_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number_one',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number_two',
        ),
    ]
