# Generated by Django 5.0.1 on 2025-04-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_passenger_seat_number_one_passenger_seat_number_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='seat_number_one',
            new_name='seat_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number_two',
        ),
    ]
