# Generated by Django 5.0.1 on 2025-04-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_rename_seat_number_one_passenger_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number',
        ),
    ]
