# Generated by Django 5.0.1 on 2025-04-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_remove_passenger_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number_two',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
