# Generated by Django 5.0.1 on 2025-04-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_passenger_seat_number_passenger_seat_number_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='seat_number',
            new_name='seat_number_one',
        ),
    ]
